### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by zeinjendeya** [GSG-G9/calorie-tracker#50]
use button component from the Material UI library to use multiple times in the app

**Comment by imansedky5** [comment]
# MainButton Component

## Acceptance Criteria
- [ ] Props
- [ ] Snapshot

---

### Props
- fontSize
- fontColor

---

### Snapshot

![](https://i.imgur.com/1lVThhQ.png)
![Screenshot_2021-02-01_23-29-31](https://user-images.githubusercontent.com/50516081/106520443-7baa9f80-64e5-11eb-919f-0462b6c494af.png)
